AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy a parameterized EC2 instance with SSH access

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t3.micro
    Description: EC2 instance type

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: The EC2 KeyPair to allow SSH access to the instance

  EnvironmentName:
    Type: String
    Description: Name of the environment (e.g., dev, prod)

  SSHLocation:
    Type: String
    Description: IP range for SSH access (CIDR)
    Default: 0.0.0.0/0

Resources:
  SecurityGroupNested:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cf-lab-stacks-20250731.s3.amazonaws.com/security-group.yml
      Parameters:
        SSHLocation: !Ref SSHLocation

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - Fn::GetAtt: [SecurityGroupNested, Outputs.SecurityGroupId]
      ImageId: ami-01dd5f7dda5e8bb39
      Tags:
        - Key: Name
          Value: !Sub "${EnvironmentName}-instance"
